services:
    # --------------------------------------------------
    # PHP-FPM Laravel Application
    # --------------------------------------------------
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: translation_app
        restart: unless-stopped
        environment:
            SERVICE_NAME: translation_app
        volumes:
            - ./:/var/www/html
            - ./storage:/var/www/html/storage
        depends_on:
            - db
            - cdn
        networks:
            translation_network:
                ipv4_address: 172.29.0.10

    # --------------------------------------------------
    # Nginx Web Server
    # --------------------------------------------------
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: translation_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - app
        networks:
            translation_network:
                ipv4_address: 172.29.0.11

    # --------------------------------------------------
    # MySQL 9 Database
    # --------------------------------------------------
    db:
        image: mysql:9.4.0
        container_name: translation_db
        restart: unless-stopped
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: translation_service
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - mysql_data:/var/lib/mysql
        networks:
            translation_network:
                ipv4_address: 172.29.0.2

    # --------------------------------------------------
    # MinIO (Local CDN / S3-Compatible)
    # --------------------------------------------------
    cdn:
        image: minio/minio:latest
        container_name: translation_cdn
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        ports:
            - "9000:9000"  # S3 API endpoint
            - "9001:9001"  # MinIO web console
        volumes:
            - minio_data:/data
        networks:
            translation_network:
                ipv4_address: 172.29.0.12

# --------------------------------------------------
# Networks & Volumes
# --------------------------------------------------
networks:
    translation_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/16

volumes:
    mysql_data:
    minio_data:
